### ISSUE TITLE
Exception when running on NixOS

### ISSUE THREAD

**Issue by eopb** [faldor20/jj_tui#6]
Hey, thanks for your work on jj tui. I'd love to give it a try, but I'm having trouble getting it running. Hopefully this error will be helpful for your debugging

```
 : nix run github:faldor20/jj_tui
Fatal error: exception Failure("selectable:3 revs:4")
Raised at Stdlib.failwith in file "stdlib.ml", line 29, characters 17-33
Called from Dune__exe__Jj_widgets.Make.graph_and_revs in file "jj_tui/bin/jj_widgets.ml", line 247, characters 9-84
Called from Dune__exe__Graph_view.Make.graph_view.(fun) in file "jj_tui/bin/graph_view.ml", line 367, characters 22-47
Called from Lwd.sub_sample.aux in file "lib/lwd/lwd.ml", line 583, characters 30-57
Called from Lwd.sub_sample.aux in file "lib/lwd/lwd.ml", line 582, characters 29-41
Called from Lwd.sub_sample.aux in file "lib/lwd/lwd.ml", line 582, characters 29-41
Called from Lwd.sub_sample.aux in file "lib/lwd/lwd.ml", line 584, characters 40-50
Called from Lwd.sub_sample.aux in file "lib/lwd/lwd.ml", line 584, characters 28-38
Called from Lwd.sub_sample.aux in file "lib/lwd/lwd.ml", line 582, characters 29-41
Called from Lwd.sub_sample.aux in file "lib/lwd/lwd.ml", line 584, characters 40-50
Called from Lwd.sub_sample.aux in file "lib/lwd/lwd.ml", line 582, characters 29-41
Called from Lwd.sub_sample.aux in file "lib/lwd/lwd.ml", line 584, characters 28-38
Called from Lwd.sub_sample.aux in file "lib/lwd/lwd.ml", line 582, characters 29-41
Called from Lwd.sub_sample.aux in file "lib/lwd/lwd.ml", line 583, characters 45-57
Called from Lwd.sub_sample.aux in file "lib/lwd/lwd.ml", line 582, characters 29-41
Called from Lwd.sub_sample.aux in file "lib/lwd/lwd.ml", line 583, characters 45-57
Called from Lwd.sub_sample.aux in file "lib/lwd/lwd.ml", line 582, characters 29-41
Called from Lwd.sub_sample.aux in file "lib/lwd/lwd.ml", line 584, characters 40-50
Called from Lwd.sub_sample.aux in file "lib/lwd/lwd.ml", line 584, characters 28-38
Called from Lwd.sub_sample.aux in file "lib/lwd/lwd.ml", line 582, characters 29-41
Called from Lwd.sub_sample.aux in file "lib/lwd/lwd.ml", line 583, characters 45-57
Called from Lwd.sub_sample.aux in file "lib/lwd/lwd.ml", line 583, characters 32-44
Called from Lwd.sub_sample.aux in file "lib/lwd/lwd.ml", line 583, characters 32-44
Called from Lwd.sub_sample.aux in file "lib/lwd/lwd.ml", line 583, characters 32-44
Called from Lwd.sub_sample.aux in file "lib/lwd/lwd.ml", line 583, characters 32-44
Called from Lwd.sub_sample.aux in file "lib/lwd/lwd.ml", line 583, characters 32-44
Called from Lwd.sub_sample.aux in file "lib/lwd/lwd.ml", line 584, characters 40-50
Called from Lwd.sub_sample.aux in file "lib/lwd/lwd.ml", line 582, characters 29-41
Called from Lwd.sub_sample.aux in file "lib/lwd/lwd.ml", line 583, characters 45-57
Called from Lwd.sub_sample.aux in file "lib/lwd/lwd.ml", line 582, characters 29-41
Called from Lwd.sub_sample.aux in file "lib/lwd/lwd.ml", line 616, characters 12-33
Called from Lwd.sub_sample.aux in file "lib/lwd/lwd.ml", line 616, characters 12-33
Called from Lwd.sub_sample.aux in file "lib/lwd/lwd.ml", line 582, characters 29-41
Called from Lwd.sample in file "lib/lwd/lwd.ml", line 678, characters 18-47
Called from Lwd.quick_sample in file "lib/lwd/lwd.ml", line 719, characters 8-25
Re-raised at Lwd.quick_sample in file "lib/lwd/lwd.ml", line 721, characters 53-62
Called from Nottui__Nottui_main.Ui_loop.step.stabilize in file "forks/nottui/lib/nottui/nottui_main.ml", line 947, characters 19-40
Called from Nottui__Nottui_main.Ui_loop.step in file "forks/nottui/lib/nottui/nottui_main.ml", line 954, characters 6-18
Called from Dune__exe__Main.ui_loop.loop in file "jj_tui/bin/main.ml", line 30, characters 6-136
Called from Eio__core__Switch.run_internal in file "lib_eio/core/switch.ml", line 133, characters 8-12
Re-raised at Eio__core__Switch.maybe_raise_exs in file "lib_eio/core/switch.ml", line 119, characters 21-56
Called from Eio__core__Switch.run_internal in file "lib_eio/core/switch.ml", line 149, characters 4-21
Called from Eio__core__Cancel.with_cc in file "lib_eio/core/cancel.ml", line 118, characters 8-12
Re-raised at Eio__core__Cancel.with_cc in file "lib_eio/core/cancel.ml", line 120, characters 50-58
Called from Eio__core__Switch.run_internal in file "lib_eio/core/switch.ml", line 133, characters 8-12
Re-raised at Eio__core__Switch.maybe_raise_exs in file "lib_eio/core/switch.ml", line 119, characters 21-56
Called from Eio__core__Switch.run_internal in file "lib_eio/core/switch.ml", line 149, characters 4-21
Called from Eio__core__Cancel.with_cc in file "lib_eio/core/cancel.ml", line 118, characters 8-12
Re-raised at Eio__core__Cancel.with_cc in file "lib_eio/core/cancel.ml", line 120, characters 50-58
Called from Eio_unix__Thread_pool.run in file "lib_eio/unix/thread_pool.ml", line 108, characters 8-13
Re-raised at Eio_unix__Thread_pool.run in file "lib_eio/unix/thread_pool.ml", line 113, characters 4-39
Called from Eio_linux__Sched.run.(fun) in file "lib_eio_linux/sched.ml", line 487, characters 22-90
Re-raised at Eio_linux__Sched.run in file "lib_eio_linux/sched.ml", line 498, characters 22-57
Called from Eio_linux__Sched.with_eventfd in file "lib_eio_linux/sched.ml", line 525, characters 8-18
Re-raised at Eio_linux__Sched.with_eventfd in file "lib_eio_linux/sched.ml", line 530, characters 4-39
Called from Eio_linux__Sched.with_sched in file "lib_eio_linux/sched.ml", line 559, characters 8-222
Re-raised at Eio_linux__Sched.with_sched in file "lib_eio_linux/sched.ml", line 572, characters 8-43
Called from Dune__exe__Main.start in file "jj_tui/bin/main.ml", line 53, characters 15-79
```

**Comment by faldor20** [comment]
Awesome thanks for the error!

Its related to displaying the graph. Could you send me the full output of the commit graph.

Eg: `JJ log >> log` and then send the log file.

**Comment by faldor20** [comment]
Basically as a safeguard we don't render the graph if we can't determine what to show for each revision. I don't want you to be able to accidentally select and perform an interaction on a revision you cannot see.

**Comment by eopb** [comment]
Sorry for taking a while to reply

Here's my `jj log` output

```
@  qpnrvwyl ethanboxx 13 seconds ago 48829167
│  (no description set)
◆  pqvkrmkw ethanboxx 3 months ago main v0.1.10 HEAD@git 931019c4
│  (empty) Merge pull request #63 from eopb/release-plz-2024-05-11T09-14-47Z
~  (elided revisions)
│ ○  xnyvmlur ethanboxx 5 months ago push-znvwmrtqnnlq 0deaa0aa
├─┘  feat: impl `Deref` and `DerefMut` without exposing `Secret`
◆  kkzuqwxo ethanboxx 5 months ago 9aa340cc
│  (empty) Merge pull request #56 from eopb/push-smksztlxprww
~
```

The project I'm trying this on is https://github.com/eopb/redact.

My `jj` configuration looks like this:

```toml
[git]
auto-local-branch = true

[revset-aliases]
"human()" = "all() ~ (author(tl-renovate) | author(dependabot))"
"interesting()" = "ancestors(mine() ~ ::trunk(), 2) | trunk() | @"

[revsets]
log = "@ | ancestors(immutable_heads().., 2) ~ (author(tl-renovate) | author(dependabot)) | trunk()"

[signing]
backend = "ssh"
key = "/home/ethan/.ssh/id_ed25519_jj.pub"
sign-all = true

[template-aliases]
"format_short_signature(signature)" = "signature.username()"
"format_timestamp(timestamp)" = "timestamp.ago()"

[templates]
log_node = "builtin_log_node"
op_log_node = "builtin_op_log_node"

[ui]
default-command = "log"
editor = "/nix/store/d2nclknw4s0xcsf547wgnl6mdwmpk695-helix-24.07/bin/hx"
log-word-wrap = true
pager = "/nix/store/1hjy5536gvxs11hkzb13f1mwm2p5zjv6-less-661/bin/less -FRX"

[ui.graph]
style = "square"

[user]
email = "ethanboxx@gmail.com"
name = "Ethan Brierley"
```
